# Generated by Django 3.0.10 on 2020-09-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
